#!/usr/bin/env python3
"""
Dynamic testing system validation - tests fully LLM-based spec and test generation
"""

import os
import sys
from dotenv import load_dotenv

# 添加src目录到Python路径
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'src'))

from main import GorillaTestSystem

def main():
    """Dynamic testing validation"""
    
    print("🚀 Fully dynamic vulnerability exploration system test")
    print("=" * 60)
    print("💡 All specifications, invariants, and test logic are dynamically generated by the LLM")
    print("=" * 60)
    
    # Load environment variables
    load_dotenv()
    
    # Set project path
    project_path = os.path.join(os.path.dirname(__file__), 'test-project')
    
    # Create test system
    system = GorillaTestSystem(project_path)
    
    # Test cases: fully dynamically generated
    test_cases = [
        {
            "name": "Dynamic Exploit Test",
            "description": "Analyze the mint function of an ERC20 contract, find access control vulnerabilities, and exploit them"
        },
        {
            "name": "Dynamic Spec Violation Detection",
            "description": "Generate formal specifications for an ERC20 contract and detect whether the mint function violates access control invariants"
        },
        {
            "name": "Dynamic Allowance Test",
            "description": "Analyze the implementation of transferFrom and detect potential allowance mechanism vulnerabilities"
        }
    ]
    
    for i, test_case in enumerate(test_cases, 1):
        print(f"\n🎯 Test {i}: {test_case['name']}")
        print(f"📝 Description: {test_case['description']}")
        print("=" * 60)
        
        try:
            success = system.generate_and_run_test(test_case['description'])
            
            print("=" * 60)
            if success:
                print(f"✅ {test_case['name']} - Dynamic generation and execution succeeded!")
                
                # Check the generated test file
                from pathlib import Path
                test_file = Path(project_path) / "test" / "GorillaTest.t.sol"
                if test_file.exists():
                    with open(test_file, 'r') as f:
                        content = f.read()
                    
                    # Check whether it contains dynamically generated content
                    if "vm.prank" in content or "token.mint" in content or "token.transferFrom" in content:
                        print("🎉 Detected dynamically generated concrete test logic!")
                    if "assertTrue" in content or "assertEq" in content:
                        print("🎉 Detected dynamically generated verification assertions!")
                        
            else:
                print(f"❌ {test_case['name']} - Execution failed")
                
        except Exception as e:
            print(f"❌ Error occurred: {e}")
            import traceback
            traceback.print_exc()
        
        if i < len(test_cases):
            input(f"\nPress Enter to continue to the next test...")
    
    print(f"\n🎉 Dynamic testing system validation completed!")
    print("📊 System features:")
    print("  ✅ Specifications are completely generated by the LLM")
    print("  ✅ Test logic is completely generated by the LLM")
    print("  ✅ Does not rely on predefined functions or templates")
    print("  ✅ Supports vulnerability analysis of any complexity")

if __name__ == "__main__":
    main()
